### PR TITLE
Adding ability to list and create notes on issues (comments)

### PR DESCRIPTION
**Pull request by jjimenezlopez**
Adding ability to list and create notes on issues (comments)

### CODE REVIEW

**Comment by dave-irvine** [comment]
Nice :) :+1:

**Comment by moul** [comment]
:ok_hand: nice, I will release the 1.3.0 today

**Comment by moul** [comment]
https://github.com/node-gitlab/node-gitlab/tree/v1.3.0 just released on https://www.npmjs.com/package/gitlab

**Comment by jjimenezlopez** [comment]
Great : )

**Pull request merged**
