### PR TITLE
Ability to list more than 20 milestones for each project

### LINKED ISSUE #96: allow parameter per_page for projectMilestones
Hey,
i have more than 20 milestones. Problem is with current implementation one can only see the last 20. Like this.
Gonna submit a PR in some hours.
See: https://github.com/Itxaka/pyapi-gitlab/issues/37

### PR DESCRIPTION
**Pull request by spruce**
I have written some small changes, so that one can list more than 20 milestones. 
See: https://github.com/node-gitlab/node-gitlab/issues/96

Also included an edited example to show how to use it. I currently don't have access to coffee compiler that's why I can't include changes to the js files.
closes #96

### CODE REVIEW

**Comment by dave-irvine** [comment]
Hi,

Thanks for your pull request.

I've taken a look, and I'm wondering if we could make it a little more like some of the other Types that are more fleshed out (ProjectMilestones was added recently from another pull request).

Take a look at: https://github.com/node-gitlab/node-gitlab/blob/develop/src/Models/Groups.coffee#L12

This takes a `params` parameters, not unlike your `query` parameter, but we also have code for recursively calling the function to make sure we fetch all the records.

Hope this doesn't discourage you!

**Comment by spruce** [comment]
That looks great. Gonna change it. to recursivly get all.

**Comment by spruce** [comment]
only problem: why give the option of setting parameter. because it will always get all records starting at the page stated. Or am I wrong? Than the params parameter could be omitted

**Comment by dave-irvine** [comment]
Haha, yeah, thinking about it it seems a bit stupid for `all()` to allow you to specify where to start. `all()` should not do this.

As you have written `list()`, it may well be that you want to accept `params` to influence where you start listing from.

Or change your function to be called `all()`, and don't take `params`. We can fix `Groups` later.

Good spot :)

**Comment by spruce** [comment]
Am I wrong to assume that https://github.com/node-gitlab/node-gitlab/blob/develop/src/Models/Groups.coffee#L34 should read
```
@get "groups", params, (data) => cb data
```
calling the function which was written for recursion?

**Comment by dave-irvine** [comment]
I've given you a really crappy example!

Check https://github.com/node-gitlab/node-gitlab/blob/develop/src/Models/Projects.coffee#L37 for one that I know works.

I think this proves I definitely need to refactor 90% of this project with tests.

**Comment by spruce** [comment]
> I think this proves I definitely need to refactor 90% of this project with tests.
Right. Also apparently tests are only failing for node 0.8

**Comment by dave-irvine** [comment]
I've taken the easy road and dropped 0.8 from our travis builds.

For some reason it was trying to install a specific version of Debug. I wonder if one of our deps is doing it.

**Comment by spruce** [comment]
So is it ready for merge than?

**Pull request merged**
