### PR TITLE
Add function to query all projects as admin

### PR DESCRIPTION
**Pull request by hessphil**
With this function it is now possible to query all projects with admin rights as described in #125

### CODE REVIEW

**Comment by moul** [comment]
LGTM

**Comment by hessphil** [comment]
Thanks :+1: 
Is there already a next release date?

**Comment by moul** [comment]
@hessphil, I will release a new version today or tomorrow

**Comment by hessphil** [comment]
Nice :+1:

**Comment by moul** [comment]
version 1.6.0 released on npm

**Pull request merged**
