### PR TITLE
Add .editorconfig file and users.search, groups.create, groups.addProject APIs

### PR DESCRIPTION
**Pull request by huhgawz**
- Add `.editorconfig` file
- Add `users.search`, `groups.create`, `groups.addProject` APIs

### CODE REVIEW

**Comment by dave-irvine** [comment]
What version of coffee are you using that is replacing

```__bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };```

with

```bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };```

?

**Comment by huhgawz** [comment]
1.9.1

**Comment by huhgawz** [comment]
Will you guys merge this pull request?

**Comment by dave-irvine** [comment]
Once I fix the mess I just made I will merge this in.

Probably best not to commit the compiled files and we will compile as part of the release as this makes the diffs hard to read.

**Comment by dave-irvine** [comment]
Merged.

**Pull request closed without merging**
