### PR TITLE
Fixed API doc, merge request acceptance and protect branch with parameters

### PR DESCRIPTION
**Pull request by mribeiro**
This pull request introduces three changes (probably should have made 3 pull requests, will happen next time):

- README.md: changed the API link as it was pointing to v4 and this module supports v3;
- ProjectMergeRequests.js/ProjectMergeRequests.coffee : new function `merge` to accept merge requests;
- ProjectRepository.js/ProjectRepository.coffee : function `protectBranch` is now accepting parameters for PUT request body.

### CODE REVIEW

**Comment by mribeiro** [comment]
@dave-irvine This should be fine now. Sorry about all the mess.

**Comment by mribeiro** [comment]
Any idea when this will enter npm repo?

**Comment by dave-irvine** [comment]
@mribeiro not sure really, usually @moul cuts the releases but I know both he and I haven't really been able to maintain this library recently, I don't use gitlab any more so I don't have much motivation to do things like the big rewrite that needs to happen, so at the moment I don't even know how to cut the release!

**Comment by mribeiro** [comment]
@dave-irvine ok, no problem. I still have my repo and will continue to use and collaborate to this one. You'll get any progress I make in the lib ;)

**Pull request merged**
