### PR TITLE
feat: Add support for Issue Statistics 

### PR DESCRIPTION
**Pull request by Stix89**

### CODE REVIEW

**Comment by casz** [comment]
link to see current commit author: https://github.com/jdalrymple/node-gitlab/pull/481/commits/51d15e295b75b6c373f4db5b16ee3fdbc03a5925

@Stix89 
You might want to set up an email alias on your GitHub account 🥇
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

Or look into fixing your git user.email config 😅  
https://help.github.com/articles/setting-your-commit-email-address-in-git
then you would need to amend your commits: https://stackoverflow.com/a/3042512
after changing author

to get proper credit for your commits 🏆

**Comment by jdalrymple** [comment]
Looks good! Only thing i would change would be the plurality of Issues. So instead of "IssuesStatistics" it should be: "IssueStatistics"

**Comment by Stix89** [comment]
ok, no probelm,  i'll wait 😄

you have any changes to advise me?
________________________________
De : Justin Dalrymple <notifications@github.com>
Envoyé : jeudi 24 octobre 2019 11:51
À : jdalrymple/node-gitlab <node-gitlab@noreply.github.com>
Cc : Stix89 <stix89@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [jdalrymple/node-gitlab] feat: Add support for Issue Statistics (#481)


Ill wait until the end of the day if you want to amend your commits to get the proper credit :)

**Comment by jdalrymple** [comment]
Nope all looks good!

**Pull request merged**
