### PR TITLE
bugfix:create MR failed,parameter assigneeId should be assignee_id. s…

### PR DESCRIPTION
**Pull request by zhangqingyv**
bugfix:create MR failed,parameter assigneeId should be assignee_id. see http://docs.gitlab.com/ce/api/merge_requests.html#create-mr

### CODE REVIEW

**Comment by mdsb100** [comment]
@moul Come here to maintain.

**Comment by mdsb100** [comment]
@dave-irvine Come here to maintain

**Comment by mdsb100** [comment]
@dave-irvine  
I hope you publish fix version as soon as possible:)

**Comment by moul** [comment]
gitlab@1.7.1 released on npm

**Pull request merged**
