### PR TITLE
feat: Add Group.projects

### PR DESCRIPTION
**Pull request by Granjow**
This commit also introduces a minimal typed response as a first step
towards #384.

### CODE REVIEW

**Comment by jdalrymple** [comment]
The only suggestion id have would be moving the interface information into the corresponding service, just for consistency.

**Comment by Granjow** [comment]
@jdalrymple Yes, I did not do this because also other endpoints return the same structure, e.g. /api/v4/projects returns projects as well. But I could move it to servcies/Projects.ts and reference it from Groups.ts?

**Comment by Granjow** [comment]
Anyone, can this MR be merged?

**Comment by jdalrymple** [comment]
Yea sorry! I though i responded :man_facepalming: I would move it into the Projects.js file!

**Comment by Granjow** [comment]
@jdalrymple Updated! I suffixed the interface with `Schema` so people do not accidentially import `Project` instead of `Projects`.

**Pull request merged**
